# Auto Arima for All companies 2
## in this notebook i have used Auto Arima Time Series to predict the stock prices there are almost like 10 years of stock prices which i have train of each company, dataset taken from kaggle, now as model is trained now we can push the current stock prices in model to get the prediction

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from subprocess import check_output
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from pandas.plotting import lag_plot
from pandas import datetime
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error

In [9]:

#TRAIN TEST SPLITTING
def traintestsplit():
    trainData, testData = df[0:int(len(df)*0.8)], df[int(len(df)*0.8):]
    return trainData,testData

#PREDICTION FUNCTIONS
def smape_kun(y_true, y_pred):#mean values
    return np.mean((np.abs(y_pred - y_true) * 200/ (np.abs(y_pred) + np.abs(y_true))))


def predictions(trainData,testData):#Auto Arima Algorithm
    training = trainData['Open'].values
    test_ar = testData['Open'].values
    psthist = [x for x in training]
    print(type(psthist))
    predicted = list()
    for t in range(len(test_ar)):
        model = ARIMA(psthist, order=(5,1,0))
        model_fit = model.fit(disp=0)
        output = model_fit.forecast()
        yhat = output[0]
        predicted.append(yhat)
        obs = test_ar[t]
        psthist.append(obs)
        #print('predicted=%f, expected=%f' % (yhat, obs))
    err = mean_squared_error(test_ar, predicted)
    print('Testing Mean Squared err: %.3f' % err)
    err2 = smape_kun(test_ar, predicted)
    print('Symmetric mean absolute percentage err: %.3f' % err2)
    return predicted





In [10]:
#trainData, testData = df[0:int(len(df)*0.8)], df[int(len(df)*0.8):]

In [11]:
import glob

In [12]:
APredictions=[]
Testdatas=[]
TrainDatas=[]
Symbols=[]
Figures=[]

In [13]:
path = r'C:/Users/Abubakar/Desktop/mpc' # use your path
all_files = glob.glob(path + "/*.csv")

for filename in all_files:#pushing all data files into the algorithm one by one
    df = pd.read_csv(filename, index_col=None, header=0)
    trainData, testData = df[0:int(len(df)*0.8)], df[int(len(df)*0.8):]
    Testdatas.append(testData)#STORING TEST DATA
    TrainDatas.append(trainData)#STORING TRAIN DATA
    
    predicted=predictions(trainData,testData)
    APredictions.append(predicted)#STORING PREDICTIONS
    symb=filename.rsplit('/', 1)[1]
    Symbols.append(symb)#STORING SYMBOLS OF COMPANIES
    
    
    print("prediction done..."+symb)
    
    

<class 'list'>
Testing Mean Squared err: 122.237
Symmetric mean absolute percentage err: 27.267
prediction done...mpc\APL.csv


In [16]:
APredictions[0]

[array([568.05488943]),
 array([586.82358048]),
 array([581.18446673]),
 array([581.5005822]),
 array([603.81157923]),
 array([599.49391399]),
 array([586.55576309]),
 array([590.04810092]),
 array([579.61149389]),
 array([606.6497587]),
 array([609.69544606]),
 array([601.17414758]),
 array([610.58799386]),
 array([620.01271606]),
 array([619.54205282]),
 array([652.71496175]),
 array([622.25457048]),
 array([621.22310606]),
 array([627.18099766]),
 array([623.96878204]),
 array([626.75272437]),
 array([622.71071716]),
 array([620.50641711]),
 array([626.78187573]),
 array([632.41803142]),
 array([652.22517363]),
 array([642.74594579]),
 array([636.93349909]),
 array([639.77473455]),
 array([638.13810118]),
 array([661.08332228]),
 array([646.0668048]),
 array([670.8481345]),
 array([684.36379736]),
 array([681.08847881]),
 array([663.54164565]),
 array([678.43069601]),
 array([678.87591949]),
 array([696.67323833]),
 array([692.02452289]),
 array([703.79985317]),
 array([713.75159267

In [15]:
Testdatas[0]

Symbol         Date    Open    High     Low   Close  Volume
2818    APL  21-Oct-2016  589.00  589.00  575.00  582.90   49900
2819    APL  24-Oct-2016  581.00  585.50  581.00  584.91   45300
2820    APL  25-Oct-2016  581.00  608.50  578.00  605.71  122600
2821    APL  26-Oct-2016  605.00  612.00  587.00  604.78  105600
2822    APL  27-Oct-2016  600.00  603.50  586.05  593.15   63200
...     ...          ...     ...     ...     ...     ...     ...
3518    APL  26-Aug-2019  265.00  270.00  256.42  258.10   20100
3519    APL  27-Aug-2019  258.00  262.90  257.99  261.82    3900
3520    APL  28-Aug-2019  263.00  272.95  263.00  263.92    6800
3521    APL  29-Aug-2019  263.41  264.00  258.10  258.87    3500
3522    APL  30-Aug-2019  258.99  264.90  249.00  258.99    3400

[705 rows x 7 columns]

In [63]:
Testdatas[3]

Symbol         Date   Open   High    Low  Close  Volume
3188   MEBL  09-May-2016  42.70  42.70  42.50  42.50  304500
3189   MEBL  10-May-2016  42.70  43.00  42.70  42.99  286500
3190   MEBL  11-May-2016  42.80  42.80  42.50  42.55    3000
3191   MEBL  12-May-2016  43.00  43.00  42.25  42.25    4000
3192   MEBL  13-May-2016  42.01  42.99  42.01  42.99    2500
...     ...          ...    ...    ...    ...    ...     ...
3981   MEBL  26-Aug-2019  77.00  77.00  74.50  75.32  139500
3982   MEBL  27-Aug-2019  75.32  75.50  73.01  74.02  691000
3983   MEBL  28-Aug-2019  74.24  77.50  73.55  76.52  825500
3984   MEBL  29-Aug-2019  77.40  78.00  75.00  75.29  184000
3985   MEBL  30-Aug-2019  75.29  77.00  74.01  75.12  319500

[798 rows x 7 columns]

In [56]:
for p in range(len(Testdatas[2].Open.values)):
    dftrue.at[p,'True']=Testdatas[2].Open.values[p]
    dftrue.at[p,'Date']=Testdatas[2].Date.values[p]
    

In [57]:
dfpred=pd.DataFrame()
for p in range(len(APredictions[2])):
    dfpred.at[p,'Predicted']=APredictions[3][p]


In [52]:
dftrue.to_csv (r'C:/Users/Abubakar/Desktop/Fatima_true.csv', index = False, header=True)

In [53]:
dfpred.to_csv (r'C:/Users/Abubakar/Desktop/AT_pred.csv', index = False, header=True)

In [75]:
dfpred.mean()/dftrue.mean()

Predicted   NaN
True        NaN
dtype: float64

In [83]:
p=dftrue.values